library(ripplerestr)
context("trustlines")

root_account <- RippleAddress("rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh")
result <- get_account_trustlines(root_account)

test_that("class is correct", {
    expect_that(is(result, "Trustline"), is_true())
    expect_that(is(result@account, "RippleAddress"), is_true())
    expect_that(is(result@counterparty, "RippleAddress"), is_true())
    expect_that(is(result@currency, "Currency"), is_true())
    expect_that(is(result@limit, "numeric"), is_true())
    expect_that(is(result@reciprocated_limit, "numeric"), is_true())
    expect_that(is(result@account_allows_rippling, "logical"), is_true())
    expect_that(is(result@counterparty_allows_rippling, "logical"), is_true())
    expect_that(is(result@ledger, "numeric"), is_true())
    expect_that(is(result@hash, "Hash256"), is_true())
})

test_that("slot lengths are equal to object length", {
    n <- length(result)
    expect_that(n, equals(length(result@account)))
    expect_that(n, equals(length(result@counterparty)))
    expect_that(n, equals(length(result@currency)))
    expect_that(n, equals(length(result@limit)))
    expect_that(n, equals(length(result@reciprocated_limit)))
    expect_that(n, equals(length(result@account_allows_rippling)))
    expect_that(n, equals(length(result@counterparty_allows_rippling)))
    expect_that(n, equals(length(result@ledger)))
    expect_that(n, equals(length(result@hash)))
})
